### ISSUE TITLE
使用yo bee新建demo产生xtemplate的runtime-min.js地址错误

### ISSUE THREAD

**Issue by ppoffice** [minghe/generator-bee#3]
在按照教程操作并使用gulp建立本地静态文件服务器后，使用浏览器打开/bee-demo/demo/dev_index.html，会出现`GET file://g.alicdn.com/kg/??xtemplate/3.3.3/runtime-min.js net::ERR_FILE_NOT_FOUND`的错误。这里明显可以看出地址应该为http/https协议。
请问这个是当前generator中存在的bug么？还是说一定要另外建立文件服务器来浏览dev_index.html呢？

**Comment by lufengd3** [comment]
@ppoffice  要从文件服务器访问html文件，看源码

```
kg: {
  base: '//g.alicdn.com/'
}
```

为了保证对https页面的支持，url都没加协议类型
